apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob
  namespace: nginx
spec:
  schedule: "* * * * *"  # Runs every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: busybox
            command: ["echo", "Hello f!"]
          restartPolicy: Never