apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-vpa-hpa
  namespace: hpa-vpa
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: hpa-vpa-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
  