apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deploymen
  namespace: scaling-scheduling

spec:
  replicas: 3

  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx

    spec:

      nodeSelector:                                             #node selector to schedule pod on specific node
        disktype: ssd

      affinity:                                                 #node affinity to schedule pod on node with specific cpu
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cpu
                operator: Gt
                values:
                - "8"

      tolerations:                                               #toleration to schedule pod on node with specific taint
      - key: "env"
        operator: "Equal"
        value: "prod"
        effect: "NoSchedule"

      containers:
      - name: nginx
        image: nginx:latest

        ports:
        - containerPort: 80

        resources:                                                #resource requests and limits for the container
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"

        startupProbe:                                              #startup probe to check if the container is started and ready to serve traffic
          httpGet:
            path: /
            port: 80
          periodSeconds: 5
          failureThreshold: 30

        readinessProbe:                                             #readiness probe to check if the container is ready to serve traffic
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:                                             #liveness probe to check if the container is running and healthy 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3


#Add labels to nodes
#kubectl label node worker1 disktype=ssd
#kubectl label node worker1 cpu=16

#Add taints to nodes
#kubectl taint nodes worker1 env=prod:NoSchedule